### ISSUE TITLE
total cases: need to compute them?

### ISSUE THREAD

**Issue by fvisconti** [alexamici/covid-19-notebooks#2]
Why do you compute `total_cases = cases + deaths + healed`? I could not find any reference on the **pcm_dpc** official data page.. Moreover, here: https://www.worldometers.info/coronavirus/ the total cases for Italy are 9172 = active + deaths + recovered.

I believe the `cases` column in **pcm_dpc** data are the `total_cases` already.

**Comment by alexamici** [comment]
I think you are right, I didn't notice because I don't use that column anymore.

Anyway I'm switching download of the original DPC data.

**Comment by alexamici** [comment]
Done
