### ISSUE TITLE
FileNotFoundError per i nuovi csv dei dati?

### ISSUE THREAD

**Issue by enricobattocchi** [alexamici/covid-19-notebooks#3]
Ciao, complimenti anche qui per il tuo lavoro.
Avevo clonato in locale il repo per farlo girare e non avevo problemi, con le ultime modifiche (notebook anche per i dati regionali) se provo a far girare ricevo errori al tentativo di lettura dei file, e in effetti `dpc-covid19-ita-regioni.csv` e `dpc-covid19-ita-andamento-nazionale.csv`, mentre c'è `covid-19-it-protezione-civile.csv` fermo ai dati del 10 marzo...
Non ho molta esperienza con Python e i notebook quindi non so se sbaglio io.

**Comment by alexamici** [comment]
Per scaricare i dati devi scommentare la riga con `covid19.data.download`, eseguire il downlaod dei dati recenti e poi ricommentarla (non serve scaricare i dati in continuazione, solo quando vengono aggiornati)

Oddio quanto fa strano rispondere agli issue GitHub in italiano!

**Comment by enricobattocchi** [comment]
Capito! Grazie, scusa l'imbranataggine :-)
